config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'posts/create'
  get 'mmd/index'
  post 'mmd/index'
  root 'mmd#index'
  get  'groups/new'
  post '/groups/:id', to: 'groups#show', as: 'group'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :groups do
    resources :posts, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api_request.rb
class ApiRequest < ApplicationRecord
  def self.make_request(date, location, price_range, category)
    url = "https://stark-brook-82296.herokuapp.com/events?date=#{date}&location=#{location}&price_range=#{price_range}&category=#{category}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    JSON.parse(response)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :posts
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :groups
  has_many :posts

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |u|
      u.provider = auth.provider
      u.uid = auth.uid
      u.name = auth.info.name
      u.oauth_token = auth.credentials.token
      u.oauth_expires_at = Time.at(auth.credentials.expires_at)
      u.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/groups_controller.rb
require 'net/http'
require 'json'

class GroupsController < ApplicationController
  def new
    @users = User.all
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    (params[:group][:user_ids]).each do |i|
      GroupUser.create({
        user_id: params[:group][:user_ids][i.to_i],
        group_id: @group.id
      })
    end
    redirect_to @group
  end

  def show
    @group = Group.find(params[:id])
    @group_posts = @group.posts
    @post = Post.new
      if params[:date] == nil && params[:location] == nil
        @events = []
      else
      @events = ApiRequest.make_request(
        params[:date],
        params[:location],
        params[:price_range],
        params[:category]
      )
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/mmd_controller.rb
require 'net/http'
require 'json'

class MmdController < ApplicationController

  def index

    if params[:date] == nil && params[:location] == nil
      @events = []
    else

    @events = ApiRequest.make_request(
      params[:date],
      params[:location],
      params[:price_range],
      params[:category]
    )

      if @events == [] 
        flash[:notice] = 'No event matches your request. Try again!'
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
    @group = Group.find_by(id: params[:group_id])
    @post = @group.posts.create(post_params)
    @post.user_id = current_user.id
    @post.save!
    redirect_to(@group)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_activities_form.html.erb
<%= stylesheet_link_tag  'form.css' %>

<div class='form' id='activities'>
  <%= form_tag(controller: 'groups', action: 'show', method: 'get') do %>
    <%= label_tag :date %>
    <%= date_field_tag(:date) %>
    <%= label_tag :location %>
    <%= select_tag :location, options_for_select(['London', 'Edinburgh']) %>
    <%= label_tag :category %>
    <%= select_tag :category, options_for_select(['Chill', 'Active', 'Culture', 'Quirky']) %>
    <%= label_tag :budget %>
    <%= select_tag :price_range, options_for_select([1,2,3,4,5]) %>
    <%= submit_tag('Make Our Day') %>
  <% end %>
</div>

app/views/groups/_group_activities_form.html.erb
<%= stylesheet_link_tag  'form.css' %>

<div class='form'>
  <%= form_tag(controller: 'groups', action: 'show') do %>
    <%= label_tag :date %>
    <%= date_field_tag(:date) %>
    <%= label_tag :location %>
    <%= select_tag :location, options_for_select(['London', 'Edinburgh']) %>
    <%= label_tag :category %>
    <%= select_tag :category, options_for_select(['Chill', 'Active', 'Culture', 'Quirky']) %>
    <%= label_tag :budget %>
    <%= select_tag :price_range, options_for_select([1,2,3,4,5]) %>
    <%= submit_tag('Make My Day') %>
  <% end %>
</div>

app/views/groups/new.html.erb
<% stylesheet_link_tag 'new_group.css' %>

<div class='group-form'>
  <%= form_for @group do |form| %>

    <div class='group-name'>
      <%= form.label 'Enter group name:' %>
      <%= form.text_area :name %>
    </div>

    <div class="users-list">
      <div>Add friends:</div>
      <div class='checklist'>
        <%= form.collection_check_boxes :user_ids, @users, :id, :name do |b| %>
          <div class='checklist-user'>
            <%= b.check_box %>
            <%= b.label %>
          </div>
        <% end %>
      </div>
    </div>

    <%= form.submit "Create Group" %>

  <% end %>



</div>

app/views/groups/show.html.erb
<%= javascript_pack_tag 'hello_react' %>


<div class='main-body'>
  <div class='calendar'>
    <div class='calendar-header'>
      <div class="calendar-month">July</div>
      <div class='week-days'>
        <div class=week-day>M</div>
        <div class=week-day>T</div>
        <div class=week-day>W</div>
        <div class=week-day>T</div>
        <div class=week-day>F</div>
        <div class=week-day>S</div>
        <div class=week-day>S</div>
      </div>
    </div>

    <div class='days'>
      <% 6.times do %>
        <div class='day'> </div>
      <% end %>
      <% @d = 0 %>
      <% 31.times do %>
        <% @d += 1 %>
        <div class='day' id='<%= @group.name + @d.to_s %>'> <%= @d %> </div>
      <% end %>
    </div>
  </div>

  <div class='chat'>
    <div class='group-info'>
      <h1 id='group'><%=@group.name%></h1>
      <% @group_users = GroupUser.where(group_id: @group.id) %>
      <% @group_users.each do |user| %>
        <span> <%= User.find_by(id: user.user_id).name %>   </span>
      <% end %>
    </div>

    <div id="group_posts">
      <% @group_posts.each do |post| %>
      <% @post_author = User.find_by(id: post.user_id) %>
      <div class='post'>
        <%= @post_author.name %>:   <em><%= post.content %></em>
      </div>
      <% end %>
    </div>

    <div id="post_form">
      <div class='post-text'>
        <%= form_for [@group, @post] do |form| %>
        <%= form.text_area :content %>
        <div class='post-submit'>
          <%= form.submit "Send Message" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

  <div id='make-my-day-form'>
    <%= render partial: 'activities_form' %>
  </div>

  <div id='events'>
    <%= render partial: 'mmd/events' %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Make My Day</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Dosis|Nothing+You+Could+Do" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Make My Day', root_url %></h1>
      <div class='header-right'>
        <% if current_user %>
          <span> Signed in as <%= current_user.name %>! </span>
          <span> <%= link_to "Sign out", signout_path, id: "sign_out" %> </span>
        <% else %>
          <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
        <% end %>

        <% if current_user %>
          <div class="dropdown">
            <button class="dropbtn">My groups</button>
            <div class="dropdown-content">
              <% @relationships = GroupUser.where(user_id: current_user.id) %>
              <% @relationships.each do |group_user| %>
              <% @group = Group.find_by(id: group_user.group_id) %>
              <%= link_to @group.name, group_path(@group)%>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </header>

    <div class='content'>
    <%= yield %>
    </div>

  </body>
</html>

app/views/mmd/_activities_form.html.erb
<%= stylesheet_link_tag  'form.css' %>

<div class='form' id='acitivities'>
  <%= form_tag(controller: 'mmd', action: 'index', method: 'get') do %>
    <%= label_tag :date %>
    <%= date_field_tag(:date) %>
    <%= label_tag :location %>
    <%= select_tag :location, options_for_select(['London', 'Edinburgh']) %>
    <%= label_tag :category %>
    <%= select_tag :category, options_for_select(['Chill', 'Active', 'Culture', 'Quirky']) %>
    <%= label_tag :budget %>
    <%= select_tag :price_range, options_for_select([1,2,3,4,5]) %>
    <%= submit_tag('Make My Day') %>
  <% end %>
  <%= flash[:notice] %>
</div>

app/views/mmd/_events.html.erb
<%= stylesheet_link_tag 'events.css' %>

<% @events.each do |event| %>
  <div class='event'>
    <div class='event-img'>
      <%= image_tag event['images'] %>
    </div>

    <div class='event-info'>
      <div class='cat-price-loc'>
        <div class='category'> <%= event['category'] %> </div>
        <% event['price_range'].to_i.times do %>
          <div class='price'>£</div>
        <% end %>
        <div class='location'> <%= event['location'] %> </div>
      </div>

      <h2><%= event['title'] %></h2>
      <div class='description'>
        <div class= 'what-is-it'>What is it?</div>
        <%= event['description'] %>
      </div>
      <%= link_to 'Visit website', event['url'] %>
    </div>
  </div>

<% end %>

app/views/mmd/index.html.erb
<%= stylesheet_link_tag  'index.css' %>

<div class='banner'>
  <%= link_to 'Make My Day', '#make-my-day-form' %>
  <%= link_to 'Make Our Day', new_group_path %>
</div>

<div id='make-my-day-form'>
  <%= render 'activities_form' %>
</div>

<div id='events'>
  <%= render 'events' %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>